"""Auto-generated technical skill vocabulary (LLM-extracted).

Regenerate with: python scripts/build_skill_vocab_llm.py
Source: extracted_skills.jsonl; doc-frequency threshold >= 5.
"""

SKILLS_VOCABULARY: list[str] = [
    'A/B testing',
    'Access',
    'access management systems',
    'Active Directory',
    'Agile',
    'agile methodologies',
    'AI',
    'AI/ML',
    'Ajax',
    'Alibaba Cloud',
    'Alteryx',
    'Amazon Redshift',
    'Analytics',
    'Android',
    'Angular',
    'anomaly detection',
    'Ansible',
    'antivirus',
    'Apache Airflow',
    'Apache Kafka',
    'Apache NiFi',
    'Apache Spark',
    'API testing',
    'APM',
    'Appium',
    'application security',
    'Architecture',
    'ArcSight',
    'Argo',
    'ArgoCD',
    'ASP.NET',
    'Authentication',
    'automated testing',
    'automation',
    'automation scripts',
    'AWS',
    'AWS Certified Solutions Architect',
    'AWS Glue',
    'AWS S3',
    'AWS SageMaker',
    'Axon',
    'Azure',
    'Azure AI',
    'Azure Data Factory',
    'Azure DevOps',
    'Azure Security Engineer Associate',
    'Bash',
    'BI',
    'Big Data',
    'BigQuery',
    'BPMN',
    'BRD',
    'Bugzilla',
    'business analysis',
    'Business Intelligence',
    'business process modeling',
    'C#',
    'C++',
    'CA',
    'CAP',
    'Cassandra',
    'CBAP',
    'CCBA',
    'CCIE',
    'CCNA',
    'CCNP',
    'CCPA',
    'CCSP',
    'CDMP',
    'CDN',
    'CEH',
    'CFA',
    'Chatbots',
    'Chef',
    'CI/CD',
    'CircleCI',
    'CISA',
    'Cisco ASA',
    'CISM',
    'CISSP',
    'CKA',
    'CKAD',
    'classification',
    'Claude',
    'cloud architecture',
    'Cloud Build',
    'cloud computing',
    'cloud infrastructure',
    'cloud migration',
    'cloud platforms',
    'cloud security',
    'Cloud SQL',
    'Cloud Storage',
    'CloudFormation',
    'Clustering',
    'code reviews',
    'compliance',
    'CompTIA Security+',
    'Compute',
    'Compute Engine',
    'computer vision',
    'Confluence',
    'container orchestration',
    'containerization',
    'CRISC',
    'CRM',
    'CSS3',
    'Cyber Kill Chain',
    'cybersecurity',
    'cybersecurity policies',
    'Cypress',
    'Cysa+',
    'dashboards',
    'DAST',
    'data analysis',
    'data architecture',
    'data cleansing',
    'Data Engineering',
    'Data Fusion',
    'data governance',
    'data integration',
    'data integrity',
    'data lakes',
    'Data Loss Prevention',
    'data management',
    'Data Manipulation',
    'data mining',
    'Data Modeling',
    'data pipelines',
    'data processing',
    'data profiling',
    'Data Quality',
    'Data Quality Management',
    'Data Science',
    'Data Security',
    'data validation',
    'data visualization',
    'Data Warehouse',
    'database management',
    'Datadog',
    'Dataflow',
    'DataOps',
    'DAX',
    'Deep Learning',
    'Design Thinking',
    'DevOps',
    'DevSecOps',
    'DHCP',
    'dimensional modeling',
    'Disaster Recovery',
    'Distributed Computing',
    'distributed systems',
    'Django',
    'DLP',
    'DNS',
    'Docker',
    'documentation',
    'EC2',
    'EDC',
    'EDR',
    'EKS',
    'Elasticsearch',
    'ELK',
    'ELT',
    'embeddings',
    'encryption',
    'Endpoint Security',
    'ERP',
    'ETL',
    'Excel',
    'FAISS',
    'FastAPI',
    'feature engineering',
    'Figma',
    'FinOps',
    'Firebase',
    'firewalls',
    'Flink',
    'forecasting',
    'forensic analysis',
    'functional testing',
    'GCFA',
    'GCFE',
    'GCIA',
    'GCIH',
    'GCP',
    'GDPR',
    'Generative AI',
    'GIS',
    'Git',
    'GitHub',
    'GitHub Actions',
    'GitLab',
    'GitLab CI',
    'GitOps',
    'GKE',
    'Go',
    'Google Analytics',
    'Google BigQuery',
    'Grafana',
    'GRC',
    'GREM',
    'GSEC',
    'Hadoop',
    'HBase',
    'Helm',
    'Hibernate',
    'high availability',
    'HIPAA',
    'Hive',
    'HTML',
    'HTML5',
    'HTTP',
    'Hugging Face',
    'IAM',
    'identity and access management',
    'IDQ',
    'IDS/IPS',
    'incident response',
    'Informatica PowerCenter',
    'Infrastructure as Code',
    'integration testing',
    'iOS',
    'IoT',
    'ISO 27001',
    'ISO 9001',
    'ISTQB',
    'ITIL',
    'Java',
    'JavaScript',
    'Jenkins',
    'Jira',
    'JMeter',
    'jQuery',
    'JSON',
    'Juniper',
    'JUnit',
    'Kanban',
    'Keras',
    'Kibana',
    'KPIs',
    'Kubeflow',
    'Kubernetes',
    'Lambda',
    'LangChain',
    'LDAP',
    'Lean',
    'Linux',
    'Linux/Unix',
    'LLM',
    'Load Balancing',
    'logging',
    'LogRhythm',
    'Looker',
    'Machine Learning',
    'Malware Analysis',
    'manual testing',
    'Matlab',
    'matplotlib',
    'Maven',
    'MDM',
    'Metabase',
    'Metadata Management',
    'microservices',
    'Microsoft Defender for Cloud',
    'Microsoft Office',
    'Microsoft Sentinel',
    'Microsoft Visio',
    'MITRE ATT&CK',
    'ML',
    'MLflow',
    'MLOps',
    'model evaluation',
    'MongoDB',
    'monitoring',
    'MS Project',
    'MVC',
    'MySQL',
    'Nagios',
    'NCA',
    'NDMO',
    'NET',
    'network',
    'network monitoring solutions',
    'network security',
    'networking',
    'neural networks',
    'Nexus',
    'Nginx',
    'NiFi',
    'NIST',
    'NLP',
    'NLTK',
    'Node.js',
    'NoSQL',
    'NumPy',
    'observability',
    'OCI',
    'OLAP',
    'ONNX',
    'OpenAI',
    'OpenCV',
    'OpenShift',
    'OpenStack',
    'OSCP',
    'PaaS',
    'Pandas',
    'PCI DSS',
    'PDPL',
    'Penetration Testing',
    'performance testing',
    'Performance Tuning',
    'PHP',
    'PKI',
    'PL/SQL',
    'Playwright',
    'PMP',
    'PostgreSQL',
    'Postman',
    'Power Apps',
    'Power Automate',
    'Power BI',
    'Power Query',
    'PowerPoint',
    'PowerShell',
    'predictive analytics',
    'predictive modeling',
    'Primavera P6',
    'project management',
    'project management methodologies',
    'Prometheus',
    'prompt engineering',
    'protocols',
    'PSD2',
    'Pub/Sub',
    'Puppet',
    'Python',
    'PyTorch',
    'QA',
    'QlikView',
    'QRadar',
    'quality assurance',
    'RabbitMQ',
    'RAG',
    'Ray',
    'RDBMS',
    'RDS',
    'React',
    'React Native',
    'Red Hat OpenShift',
    'Redis',
    'Redshift',
    'regression',
    'regression testing',
    'reinforcement learning',
    'reporting',
    'REST',
    'REST API',
    'Rest Assured',
    'Reverse Engineering',
    'risk assessment',
    'risk management',
    'routers',
    'routing',
    'RPA',
    'Ruby',
    'S3',
    'SaaS',
    'SageMaker',
    'SAN',
    'SAST',
    'SCADA',
    'Scala',
    'scikit-learn',
    'scripting',
    'Scrum',
    'SDLC',
    'security',
    'security operations center',
    'Selenium',
    'serverless',
    'SharePoint',
    'Shell',
    'Shell scripting',
    'SIEM',
    'Snowflake Schema',
    'SOAP',
    'SoapUI',
    'SOAR',
    'Software Development',
    'spaCy',
    'Spotfire',
    'Spring',
    'Spring Boot',
    'SPSS',
    'SQL',
    'SQL Server',
    'SSIS',
    'SSL',
    'SSO',
    'stakeholder management',
    'Star Schema',
    'statistical analysis',
    'statistical modeling',
    'statistics',
    'Storage',
    'SVN',
    'Switches',
    'System Administration',
    'T-SQL',
    'Tableau',
    'Talend',
    'TCP/IP',
    'TDD',
    'TensorFlow',
    'Terraform',
    'testing',
    'TestNG',
    'TestRail',
    'TFS',
    'Threat Hunting',
    'threat intelligence',
    'TLS',
    'TOGAF',
    'Transformers',
    'Trello',
    'TypeScript',
    'UAT',
    'Ubuntu',
    'UML',
    'unit testing',
    'Unix',
    'vector databases',
    'version control',
    'Vertex AI',
    'virtualization',
    'Visio',
    'Visualization',
    'visualization tools',
    'VMware',
    'VMware Cloud Director',
    'VPC',
    'VPN',
    'vSAN',
    'vulnerability assessment',
    'vulnerability management',
    'Waterfall',
    'web services',
    'Whisper',
    'Windows',
    'Word',
    'XDR',
    'XML',
    'Zero Trust',
]

SKILL_ALIASES = {
    "airflow": "Apache Airflow",
    "ci cd": "CI/CD",
    "ci-cd": "CI/CD",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "k8s": "Kubernetes",
    "kafka": "Apache Kafka",
    "microsoft excel": "Excel",
    "ms excel": "Excel",
    "node js": "Node.js",
    "nodejs": "Node.js",
    "postgres": "PostgreSQL",
    "power bi": "Power BI",
    "powerbi": "Power BI",
    "rest api": "REST API",
    "rest apis": "REST API",
    "restful": "REST API",
    "scikit learn": "scikit-learn",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "spark": "Apache Spark"
}

SKILL_SYNONYMS = {
    "artificial intelligence": "AI",
    "cloud services": "cloud platforms",
    "cloud technologies": "cloud platforms",
    "data analytics": "Data Analysis",
    "data modeling": "Data Modeling",
    "data modelling": "Data Modeling",
    "data models": "Data Modeling",
    "data warehouses": "Data Warehouse",
    "data warehousing": "Data Warehouse",
    "elk stack": "ELK",
    "gen ai": "Generative AI",
    "genai": "Generative AI",
    "gitlab ci/cd": "GitLab CI",
    "golang": "Go",
    "google cloud": "GCP",
    "google cloud platform": "GCP",
    "iac": "Infrastructure as Code",
    "infrastructure-as-code": "Infrastructure as Code",
    "intrusion detection systems": "IDS/IPS",
    "ips/ids": "IDS/IPS",
    "large language models": "LLM",
    "llms": "LLM",
    "microservices architecture": "microservices",
    "microsoft azure": "Azure",
    "microsoft office suite": "Microsoft Office",
    "microsoft power bi": "Power BI",
    "ms office": "Microsoft Office",
    "ms sql server": "SQL Server",
    "natural language processing": "NLP",
    "nosql databases": "NoSQL",
    "oracle cloud": "OCI",
    "oracle cloud infrastructure": "OCI",
    "pci-dss": "PCI DSS",
    "relational databases": "RDBMS",
    "restful apis": "REST API",
    "security+": "CompTIA Security+",
    "vpcs": "VPC",
    "vpns": "VPN"
}


def get_skill_vocabulary() -> list[str]:
    """Return the curated skill vocabulary (sorted)."""
    return list(SKILLS_VOCABULARY)
